export type T212Status = 'yes' | 'likely' | 'verify'
export type MarketCap = 'mega' | 'large' | 'mid' | 'small' | 'micro'

export interface HalalStock {
  ticker: string
  name: string
  exchange: string
  country: string
  sector: string
  score: number // 0-100
  debtRatio: number // total debt / total assets %
  interestRatio: number // interest income / revenue %
  revenueGrowth: number // YoY %
  grossMargin: number // %
  marketCap: MarketCap
  t212: T212Status
  t212Search: string // how to find on T212
  why: string // one-line reason to own
}

// AAOIFI standard: debt/assets ≤ 33%, interest income/revenue ≤ 5%
// Data as of 2024 annual reports
export const HALAL_STOCKS: HalalStock[] = [
  // ── MEGA CAP US TECH ────────────────────────────────────────────────────────
  {
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Semiconductors',
    score: 97,
    debtRatio: 14,
    interestRatio: 0.1,
    revenueGrowth: 122,
    grossMargin: 74,
    marketCap: 'mega',
    t212: 'yes',
    t212Search: 'Search "NVDA" on T212 → NVIDIA Corp',
    why: 'Powers all AI data centres — dominant and debt-light',
  },
  {
    ticker: 'MSFT',
    name: 'Microsoft Corporation',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Technology',
    score: 94,
    debtRatio: 16,
    interestRatio: 0.2,
    revenueGrowth: 16,
    grossMargin: 70,
    marketCap: 'mega',
    t212: 'yes',
    t212Search: 'Search "MSFT" on T212 → Microsoft Corp',
    why: 'Azure + Office 365 compounding cash for decades',
  },
  {
    ticker: 'GOOGL',
    name: 'Alphabet Inc.',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Technology',
    score: 90,
    debtRatio: 3,
    interestRatio: 2.0,
    revenueGrowth: 14,
    grossMargin: 57,
    marketCap: 'mega',
    t212: 'yes',
    t212Search: 'Search "GOOGL" on T212 → Alphabet Inc Class A',
    why: 'Search monopoly + cloud + AI with almost no debt',
  },
  {
    ticker: 'AAPL',
    name: 'Apple Inc.',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Technology',
    score: 87,
    debtRatio: 30,
    interestRatio: 1.0,
    revenueGrowth: 2,
    grossMargin: 46,
    marketCap: 'mega',
    t212: 'yes',
    t212Search: 'Search "AAPL" on T212 → Apple Inc',
    why: 'Strongest brand on earth, growing services revenue',
  },
  {
    ticker: 'META',
    name: 'Meta Platforms',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Technology',
    score: 84,
    debtRatio: 8,
    interestRatio: 0.2,
    revenueGrowth: 22,
    grossMargin: 82,
    marketCap: 'mega',
    t212: 'yes',
    t212Search: 'Search "META" on T212 → Meta Platforms',
    why: 'Ads + AI + VR — fast growth with minimal debt',
  },
  // ── LARGE CAP US ────────────────────────────────────────────────────────────
  {
    ticker: 'ADBE',
    name: 'Adobe Inc.',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Software',
    score: 89,
    debtRatio: 19,
    interestRatio: 0.3,
    revenueGrowth: 11,
    grossMargin: 88,
    marketCap: 'large',
    t212: 'yes',
    t212Search: 'Search "ADBE" on T212 → Adobe Inc',
    why: 'Creative suite monopoly — 88% gross margins',
  },
  {
    ticker: 'MPWR',
    name: 'Monolithic Power Systems',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Semiconductors',
    score: 88,
    debtRatio: 0,
    interestRatio: 0.2,
    revenueGrowth: 22,
    grossMargin: 55,
    marketCap: 'large',
    t212: 'yes',
    t212Search: 'Search "MPWR" on T212 → Monolithic Power',
    why: 'Zero debt, AI power management chips — perfect Halal',
  },
  {
    ticker: 'LSCC',
    name: 'Lattice Semiconductor',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Semiconductors',
    score: 86,
    debtRatio: 0,
    interestRatio: 0.1,
    revenueGrowth: 18,
    grossMargin: 69,
    marketCap: 'mid',
    t212: 'yes',
    t212Search: 'Search "LSCC" on T212 → Lattice Semiconductor',
    why: 'Low-power FPGAs for edge AI — zero debt, high margins',
  },
  {
    ticker: 'GMED',
    name: 'Globus Medical',
    exchange: 'NYSE',
    country: 'US',
    sector: 'Medical Devices',
    score: 78,
    debtRatio: 15,
    interestRatio: 0.3,
    revenueGrowth: 68,
    grossMargin: 67,
    marketCap: 'large',
    t212: 'yes',
    t212Search: 'Search "GMED" on T212 → Globus Medical',
    why: 'Spine surgery robot leader — strong growth, Halal sector',
  },
  // ── UK ───────────────────────────────────────────────────────────────────────
  {
    ticker: 'GAW.L',
    name: 'Games Workshop Group',
    exchange: 'LSE',
    country: 'UK',
    sector: 'Consumer / Leisure',
    score: 91,
    debtRatio: 5,
    interestRatio: 0.1,
    revenueGrowth: 14,
    grossMargin: 68,
    marketCap: 'small',
    t212: 'yes',
    t212Search: 'Search "GAW" on T212 → Games Workshop (LSE)',
    why: 'Warhammer IP — 68% margins, nearly zero debt, global fans',
  },
  {
    ticker: 'PSN.L',
    name: 'Persimmon PLC',
    exchange: 'LSE',
    country: 'UK',
    sector: 'Housebuilding',
    score: 72,
    debtRatio: 0,
    interestRatio: 0.5,
    revenueGrowth: -6,
    grossMargin: 21,
    marketCap: 'large',
    t212: 'yes',
    t212Search: 'Search "PSN" on T212 → Persimmon (LSE)',
    why: 'UK housing shortage play — zero debt, big dividend',
  },
  // ── SWISS / EUROPEAN ────────────────────────────────────────────────────────
  {
    ticker: 'LOGN.SW',
    name: 'Logitech International',
    exchange: 'SIX Swiss',
    country: 'Switzerland',
    sector: 'Technology',
    score: 82,
    debtRatio: 0,
    interestRatio: 0.2,
    revenueGrowth: 4,
    grossMargin: 42,
    marketCap: 'large',
    t212: 'yes',
    t212Search: 'Search "LOGN" on T212 → Logitech (Swiss)',
    why: 'Gaming peripherals + video conferencing — zero debt',
  },
  {
    ticker: 'AIXA.DE',
    name: 'AIXTRON SE',
    exchange: 'Xetra',
    country: 'Germany',
    sector: 'Semiconductors',
    score: 83,
    debtRatio: 0,
    interestRatio: 0.1,
    revenueGrowth: 26,
    grossMargin: 47,
    marketCap: 'mid',
    t212: 'likely',
    t212Search: 'Search "AIXA" on T212 → AIXTRON (Xetra)',
    why: 'Makes the machines that make power chips — zero debt',
  },
  {
    ticker: 'MYCR.ST',
    name: 'Mycronic AB',
    exchange: 'Nasdaq Stockholm',
    country: 'Sweden',
    sector: 'Industrial Tech',
    score: 80,
    debtRatio: 4,
    interestRatio: 0.2,
    revenueGrowth: 18,
    grossMargin: 52,
    marketCap: 'mid',
    t212: 'likely',
    t212Search: 'Search "MYCR" on T212 → Mycronic (Stockholm)',
    why: 'PCB assembly machines — hidden European tech gem',
  },
  {
    ticker: 'NEDAP.AS',
    name: 'Nedap NV',
    exchange: 'Euronext Amsterdam',
    country: 'Netherlands',
    sector: 'Technology',
    score: 78,
    debtRatio: 5,
    interestRatio: 0.3,
    revenueGrowth: 10,
    grossMargin: 58,
    marketCap: 'small',
    t212: 'likely',
    t212Search: 'Search "NEDAP" on T212 → Nedap (Amsterdam)',
    why: 'Dutch IoT / security systems — steady compounder',
  },
]

export const SECTOR_COLORS: Record<string, string> = {
  Semiconductors: 'bg-purple-500/20 text-purple-300',
  Technology: 'bg-blue-500/20 text-blue-300',
  Software: 'bg-cyan-500/20 text-cyan-300',
  'Medical Devices': 'bg-pink-500/20 text-pink-300',
  'Consumer / Leisure': 'bg-orange-500/20 text-orange-300',
  Housebuilding: 'bg-yellow-500/20 text-yellow-300',
  'Industrial Tech': 'bg-teal-500/20 text-teal-300',
}

export const T212_BADGE: Record<T212Status, { label: string; cls: string }> = {
  yes: { label: 'T212 ✓', cls: 'bg-green-500/20 text-green-300 border border-green-500/30' },
  likely: { label: 'T212 ~', cls: 'bg-yellow-500/20 text-yellow-300 border border-yellow-500/30' },
  verify: { label: 'Verify', cls: 'bg-orange-500/20 text-orange-300 border border-orange-500/30' },
}

// Rotation order for weekly DCA
export const DCA_ROTATION = ['NVDA', 'MSFT', 'GOOGL', 'AAPL', 'ADBE', 'MPWR', 'LSCC', 'GAW.L']
