// All stocks verified halal on Musaffa/Zoya under AAOIFI methodology
// Data from Musaffa/Zoya screening + company annual reports
// Last research: May 2026

export interface Stock {
  ticker: string
  name: string
  exchange: string
  country: string
  sector: string
  description: string          // one-line investment thesis
  musaffaGrade: string         // A+, A, A-, B+, B, B-, etc.
  musaffaStatus: 'HALAL' | 'DOUBTFUL' | 'NOT_HALAL'
  debtRatioNote: string        // qualitative note from screening
  interestIncomeRatio: number  // % of revenue — for purification calc
  purificationNote: string
  score: number                // 0-100 composite (grade + growth + moat)
  inDcaRotation: boolean
}

export const STOCKS: Stock[] = [
  // ── US TECHNOLOGY & SEMICONDUCTORS ────────────────────────────────────────
  {
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'AI / Semiconductors',
    description: 'Dominant AI chip designer powering every major data centre globally',
    musaffaGrade: 'A-',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Low debt, passes AAOIFI <30% threshold',
    interestIncomeRatio: 1.07,
    purificationNote: 'Donate ~1.07% of any dividends or realised profits to charity',
    score: 97,
    inDcaRotation: true,
  },
  {
    ticker: 'AVGO',
    name: 'Broadcom Inc.',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Semiconductors / Infrastructure Software',
    description: 'Custom AI silicon for Apple, Google & Meta; VMware software recurring revenue',
    musaffaGrade: 'A-',
    musaffaStatus: 'HALAL',
    debtRatioNote: '4.2% of market cap — well under 30% AAOIFI limit',
    interestIncomeRatio: 0.54,
    purificationNote: 'Donate ~0.54% of any dividends or realised profits to charity',
    score: 95,
    inDcaRotation: true,
  },
  {
    ticker: 'TSM',
    name: 'Taiwan Semiconductor (TSMC)',
    exchange: 'NYSE (ADR)',
    country: 'Taiwan',
    sector: 'Semiconductor Foundry',
    description: 'Manufactures 90%+ of the world\'s advanced chips; no competitor at 2–3nm',
    musaffaGrade: 'Halal',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Passes AAOIFI threshold',
    interestIncomeRatio: 1.5,
    purificationNote: 'Donate ~1.5% of any dividends or realised profits to charity',
    score: 93,
    inDcaRotation: true,
  },
  {
    ticker: 'ASML',
    name: 'ASML Holding NV',
    exchange: 'NASDAQ',
    country: 'Netherlands',
    sector: 'Semiconductor Equipment',
    description: 'Sole maker of EUV machines — the only way to print 7nm+ chips',
    musaffaGrade: 'A',
    musaffaStatus: 'HALAL',
    debtRatioNote: '1.0% of market cap — extremely low',
    interestIncomeRatio: 1.41,
    purificationNote: 'Donate ~1.41% of any dividends or realised profits to charity',
    score: 96,
    inDcaRotation: true,
  },
  {
    ticker: 'CDNS',
    name: 'Cadence Design Systems',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'EDA Software',
    description: 'Software that chip designers use to design every semiconductor on earth',
    musaffaGrade: 'B+',
    musaffaStatus: 'HALAL',
    debtRatioNote: '3.08% of market cap — passes AAOIFI',
    interestIncomeRatio: 1.92,
    purificationNote: 'Donate ~1.92% of any dividends or realised profits to charity',
    score: 89,
    inDcaRotation: true,
  },
  {
    ticker: 'ADBE',
    name: 'Adobe Inc.',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Creative & Document Software',
    description: 'Photoshop, Illustrator, Premiere & Acrobat — world\'s creative software monopoly',
    musaffaGrade: 'A',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Passes AAOIFI threshold',
    interestIncomeRatio: 0.8,
    purificationNote: 'Donate ~0.8% of any dividends or realised profits to charity',
    score: 91,
    inDcaRotation: true,
  },
  {
    ticker: 'MPWR',
    name: 'Monolithic Power Systems',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Analog Semiconductors',
    description: 'Power management chips for AI servers, EVs and industrial equipment',
    musaffaGrade: 'Halal',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Passes AAOIFI threshold',
    interestIncomeRatio: 1.2,
    purificationNote: 'Donate ~1.2% of any dividends or realised profits to charity',
    score: 88,
    inDcaRotation: true,
  },
  // ── US HEALTHCARE ──────────────────────────────────────────────────────────
  {
    ticker: 'ISRG',
    name: 'Intuitive Surgical',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Surgical Robotics',
    description: 'da Vinci robotic surgery system — 9,000+ installed, high-margin recurring revenue',
    musaffaGrade: 'B+',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Near-zero debt — one of the cleanest halal grades available',
    interestIncomeRatio: 0.3,
    purificationNote: 'Essentially no purification needed — near-zero interest income',
    score: 92,
    inDcaRotation: true,
  },
  {
    ticker: 'LLY',
    name: 'Eli Lilly and Company',
    exchange: 'NYSE',
    country: 'US',
    sector: 'Pharmaceuticals',
    description: 'Maker of Mounjaro/Zepbound — fastest-growing drugs in pharmaceutical history',
    musaffaGrade: 'A',
    musaffaStatus: 'HALAL',
    debtRatioNote: '4.82% of market cap — well under 30% AAOIFI limit',
    interestIncomeRatio: 0.39,
    purificationNote: 'Donate ~0.39% of any dividends or realised profits to charity',
    score: 94,
    inDcaRotation: true,
  },
  {
    ticker: 'GMED',
    name: 'Globus Medical',
    exchange: 'NYSE',
    country: 'US',
    sector: 'Medical Devices',
    description: 'Spinal implant systems and ExcelsiusGPS surgical robotics platform',
    musaffaGrade: 'A-',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Passes AAOIFI threshold',
    interestIncomeRatio: 1.0,
    purificationNote: 'Donate ~1.0% of any dividends or realised profits to charity',
    score: 84,
    inDcaRotation: false,
  },
  {
    ticker: 'ABT',
    name: 'Abbott Laboratories',
    exchange: 'NYSE',
    country: 'US',
    sector: 'Medical Devices / Diagnostics',
    description: 'FreeStyle Libre continuous glucose monitor — dominant CGM platform globally',
    musaffaGrade: 'B-',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Passes AAOIFI — monitor quarterly as B- is borderline',
    interestIncomeRatio: 1.5,
    purificationNote: 'Donate ~1.5% of any dividends or realised profits to charity',
    score: 80,
    inDcaRotation: false,
  },
  // ── EUROPEAN & UK ─────────────────────────────────────────────────────────
  {
    ticker: 'AZN',
    name: 'AstraZeneca PLC',
    exchange: 'NASDAQ / LSE',
    country: 'UK',
    sector: 'Oncology / Biopharmaceuticals',
    description: 'Tagrisso, Calquence and a world-class oncology pipeline growing double-digits',
    musaffaGrade: 'Halal',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Passes AAOIFI threshold',
    interestIncomeRatio: 1.2,
    purificationNote: 'Donate ~1.2% of any dividends or realised profits to charity',
    score: 87,
    inDcaRotation: false,
  },
  {
    ticker: 'PSN.L',
    name: 'Persimmon PLC',
    exchange: 'LSE',
    country: 'UK',
    sector: 'Homebuilding',
    description: 'UK\'s largest homebuilder — chronic housing shortage drives long-term demand',
    musaffaGrade: 'A+',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Very low debt — A+ is the best possible halal grade',
    interestIncomeRatio: 0.2,
    purificationNote: 'Essentially no purification needed — A+ grade with near-zero interest income',
    score: 82,
    inDcaRotation: false,
  },
  {
    ticker: 'HLMA.L',
    name: 'Halma PLC',
    exchange: 'LSE',
    country: 'UK',
    sector: 'Safety & Health Technology',
    description: '50+ consecutive years of dividend growth via niche safety tech acquisitions',
    musaffaGrade: 'A-',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Passes AAOIFI threshold',
    interestIncomeRatio: 0.9,
    purificationNote: 'Donate ~0.9% of any dividends or realised profits to charity',
    score: 86,
    inDcaRotation: true,
  },
  {
    ticker: 'AIXA.DE',
    name: 'Aixtron SE',
    exchange: 'XETRA',
    country: 'Germany',
    sector: 'Semiconductor Equipment',
    description: 'MOCVD machines for SiC/GaN power chips used in EVs and 5G infrastructure',
    musaffaGrade: 'A-',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Passes AAOIFI threshold',
    interestIncomeRatio: 1.1,
    purificationNote: 'Donate ~1.1% of any dividends or realised profits to charity',
    score: 85,
    inDcaRotation: true,
  },
  {
    ticker: 'SU.PA',
    name: 'Schneider Electric SE',
    exchange: 'Euronext Paris',
    country: 'France',
    sector: 'Energy Management / Industrial Automation',
    description: 'Electrical infrastructure for AI data centres — unprecedented demand surge',
    musaffaGrade: 'B+',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Passes AAOIFI threshold',
    interestIncomeRatio: 1.3,
    purificationNote: 'Donate ~1.3% of any dividends or realised profits to charity',
    score: 88,
    inDcaRotation: false,
  },
  {
    ticker: 'BESI.AS',
    name: 'BE Semiconductor (Besi)',
    exchange: 'Euronext Amsterdam',
    country: 'Netherlands',
    sector: 'Semiconductor Assembly Equipment',
    description: 'Die-attach and flip-chip bonding equipment for AI chiplet packaging',
    musaffaGrade: 'A',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Passes AAOIFI threshold',
    interestIncomeRatio: 0.7,
    purificationNote: 'Donate ~0.7% of any dividends or realised profits to charity',
    score: 87,
    inDcaRotation: false,
  },
  {
    ticker: 'MYCR.ST',
    name: 'Mycronic AB',
    exchange: 'Nasdaq Stockholm',
    country: 'Sweden',
    sector: 'Electronics Production Equipment',
    description: 'PCB assembly machines and photomask writers for precision electronics',
    musaffaGrade: 'A',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Passes AAOIFI threshold',
    interestIncomeRatio: 0.6,
    purificationNote: 'Donate ~0.6% of any dividends or realised profits to charity',
    score: 83,
    inDcaRotation: false,
  },
  {
    ticker: 'LOGN.SW',
    name: 'Logitech International',
    exchange: 'SIX Swiss Exchange',
    country: 'Switzerland',
    sector: 'Computer Peripherals',
    description: 'Keyboards, mice, webcams and video conferencing gear for hybrid work',
    musaffaGrade: 'Halal',
    musaffaStatus: 'HALAL',
    debtRatioNote: 'Passes AAOIFI threshold',
    interestIncomeRatio: 1.0,
    purificationNote: 'Donate ~1.0% of any dividends or realised profits to charity',
    score: 78,
    inDcaRotation: false,
  },
]

// 12-week rotation — confirmed HALAL, diversified across sectors & geographies
export const DCA_ROTATION: string[] = [
  'NVDA',    // week 1  — AI chips (US)
  'ASML',    // week 2  — EUV monopoly (EU)
  'LLY',     // week 3  — GLP-1 drugs (US)
  'AVGO',    // week 4  — custom AI silicon (US)
  'HLMA.L',  // week 5  — safety tech compounder (UK)
  'ISRG',    // week 6  — surgical robotics (US)
  'ADBE',    // week 7  — creative software (US)
  'AIXA.DE', // week 8  — SiC/GaN equipment (DE)
  'CDNS',    // week 9  — EDA software (US)
  'TSM',     // week 10 — foundry monopoly (TW/US)
  'MPWR',    // week 11 — power management chips (US)
  'GMED',    // week 12 — medical devices (US)
]
